services:

  # Books Service
  books:
    image: "ashez2000/bookstore/books"
    container_name: bookstore-books
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

    deploy:
      resources:
        limits:
          memory: 512m

    depends_on:
      - discovery

    networks:
      - bookstore

  # Discovery Service
  discovery:
    image: "ashez2000/bookstore/discovery"
    container_name: bookstore-discovery
    ports:
      - "8070:8070"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

    deploy:
      resources:
        limits:
          memory: 512m

    networks:
      - bookstore

networks:
  bookstore:
    driver: "bridge"
