server:
  port: 8080

spring:
  application:
    name: books

  config:
    import:
      - application_prod.yml

  datasource:
    uri: jdbc:h2:mem:books_db
    driverClassName: org.h2.Driver
    username: root
    password: password

  h2:
    console: true

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
